spring:
  application:
    name: Shield
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      dialect: postgresql
    mongodb:
      uri: mongodb://mongo:admin123@localhost:27017/blockchain?authSource=admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  error:
    whitelabel:
      enabled: false
    path: /error
  port: 8080
